# Generated by Django 2.2.3 on 2019-08-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('Regno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('standards', models.IntegerField()),
                ('image', models.ImageField(upload_to='faculty/')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('Regno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('standards', models.IntegerField()),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
    ]
