# Generated by Django 2.2.3 on 2019-08-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='standards',
        ),
    ]
