# Generated by Django 2.2.3 on 2019-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0002_remove_faculty_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='quali',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
