# Generated by Django 2.2.3 on 2019-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0003_faculty_quali'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentsmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('kannad', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('mathematics', models.IntegerField()),
            ],
        ),
    ]
