# Generated by Django 2.2.3 on 2019-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0005_auto_20190824_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsmarks',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
        migrations.AddField(
            model_name='studentsmarks',
            name='totalmarks',
            field=models.IntegerField(default=False),
        ),
    ]
