# Generated by Django 2.2.3 on 2019-08-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0006_auto_20190824_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='english',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='hindi',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='kannad',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='mathematics',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='science',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='social_science',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentsmarks',
            name='totalmarks',
            field=models.IntegerField(max_length=10),
        ),
    ]
