# Generated by Django 2.2.3 on 2019-08-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0007_auto_20190825_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(max_length=10)),
                ('kannad', models.IntegerField(max_length=10)),
                ('hindi', models.IntegerField(max_length=10)),
                ('science', models.IntegerField(max_length=10)),
                ('social_science', models.IntegerField(max_length=10)),
                ('mathematics', models.IntegerField(max_length=10)),
                ('totalmarks', models.IntegerField(max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='studentsmarks',
        ),
    ]
