# Generated by Django 2.2.3 on 2019-08-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0008_auto_20190825_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='english',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='hindi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='kannad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mathematics',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='science',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='social_science',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='marks',
            name='totalmarks',
            field=models.IntegerField(),
        ),
    ]
