# Generated by Django 2.2.3 on 2019-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0009_auto_20190825_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField()),
                ('kannad', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('mathematics', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='marks',
        ),
    ]
