# Generated by Django 2.2.3 on 2019-08-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0010_auto_20190825_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Regno',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='quali',
            field=models.CharField(max_length=30),
        ),
    ]
