# Generated by Django 2.2.3 on 2019-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0011_auto_20190825_0208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='marks2',
        ),
        migrations.AddField(
            model_name='faculty',
            name='english',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='hindi',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='kannad',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mathematics',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='science',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='social_science',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='totalmarks',
            field=models.IntegerField(default=False),
        ),
    ]
