# Generated by Django 2.2.3 on 2019-08-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0012_auto_20190825_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='english',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='kannad',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mathematics',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='science',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='social_science',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='totalmarks',
        ),
        migrations.AddField(
            model_name='students',
            name='english',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='hindi',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='kannad',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='mathematics',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=20),
        ),
        migrations.AddField(
            model_name='students',
            name='science',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='social_science',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='totalmarks',
            field=models.IntegerField(default=False),
        ),
    ]
