# Generated by Django 2.2.3 on 2020-02-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0013_auto_20190825_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
