# Generated by Django 2.2.3 on 2020-02-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0014_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pasword',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
