# Generated by Django 2.2.3 on 2020-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0015_faculty_pasword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Regno',
            field=models.CharField(default=False, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
