# Generated by Django 2.2.3 on 2020-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0016_auto_20200303_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadnotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
