# Generated by Django 2.2.3 on 2020-03-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0017_uploadnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadnotification',
            new_name='uploadnotificationmodel',
        ),
    ]
