# Generated by Django 2.2.3 on 2020-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app33', '0018_auto_20200328_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp1', models.IntegerField()),
            ],
        ),
    ]
